# Generated by Django 2.0.13 on 2020-04-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_test', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appcasestep',
            options={'ordering': ['id']},
        ),
    ]
