# Generated by Django 2.0.13 on 2020-04-17 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_test', '0003_auto_20200417_0906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apistep',
            options={'ordering': ['id']},
        ),
    ]
