# Generated by Django 2.0.13 on 2020-04-16 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bug_name', models.CharField(max_length=64, verbose_name='bug 名称')),
                ('bug_detail', models.CharField(max_length=200, verbose_name='bug 详情')),
                ('bug_status', models.CharField(choices=[('激活', '激活'), ('已解决', '已解决'), ('已关闭', '已关闭')], default='激活', max_length=200, null=True, verbose_name='解决状态')),
                ('bug_level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='3', max_length=10, null=True, verbose_name='严重程度')),
                ('bug_creat', models.CharField(max_length=32, verbose_name='创建人')),
                ('bug_assign', models.CharField(max_length=32, verbose_name='分配给')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Product')),
            ],
            options={
                'verbose_name': 'bug 管理',
                'verbose_name_plural': 'bug 管理',
            },
        ),
    ]
