# Generated by Django 2.0.13 on 2020-04-16 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bug', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ['id'], 'verbose_name': 'bug 管理', 'verbose_name_plural': 'bug 管理'},
        ),
    ]
